### ISSUE TITLE
Compartilhando como gerencio as contas

### ISSUE THREAD

**Issue by Izaquielnn** [jmarcelinho/MyCards#3]
Achei interessante tua ideia. Atualmente utilizo o notion pra gerenciar as contas, é bem na linha da tua proposta. É basicamente uma tabela com todas as contas aí criei uma tag pra informar a que pessoa pertence e depois crio views na tabela para cada pessoa, assim fica fácil pra tirar print e enviar as contas. Não se serve de inspiração pro projeto, mas se quiser dar uma olhada aqui tem um exemplo de como faço: [Contas no notion](https://rift-ranunculus-bfe.notion.site/d3446e915f9744e5a0f4d20908a22596?v=a058cfe26f16460487c31f835397f886).

**Comment by jmarcelinho** [comment]
Achei interessante e melhor do que usar a planilha. É uma inspiração para o que tô fazendo.
